beebotte:
        ### Set api key from your account
        api_key: 'b703f233d5d5de2f907e43122863547290cb'
        secret_key: '9b86c1e53907e43122863547290cb7907e43122863547290cb907e431228635472'

        datadog_source: 'datadog'
        smhi_source: smhi

        update: 'True'

ubidots:
        ### Set token from your account on https://app.ubidots.com/
        token: 'mVkR0X9XzMYn907e43122863547290cb'

        urlprefix: 'https://things.ubidots.com'

        datadog_source: 'datadog'
        smhi_source: smhi

        update: 'True'

borstahusenspir:
        url: 'http://seadog.ddns.net:800/rapporter/BSS.htm'
        kollaDessaClasser:
                storhetClassName: Kol_tx_storhet
                medelClassName: Kol_tx_medel
                minClassName: Kol_tx_mi
                maxClassName: Kol_tx_ma
        typeName:
                Kol_tx_medel: _medel
                Kol_tx_mi: _min
                Kol_tx_ma: _max

smhi:
        urlprefix: 'http://opendata-download-ocobs.smhi.se/api/version/latest/parameter/6/station/'
        seaLevelLocations: 
                Barseback: 2099
                Viken: 2228
                Klagshamn: 2095
                Skanor: 30488
