### Log levels: (less) CRITICAL, ERROR, WARNING, INFO, DEBUG (more)
loglevel: WARNING

beebotte:
        ### Set api key from your account
        api_key: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
        secret_key: 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'

        datadog_source: 'datadog'
        smhi_source: smhi

        update: 'True'

ubidots:
        ### Set token from your account on https://app.ubidots.com/
        token: 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'

        urlprefix: 'https://things.ubidots.com'

        datadog_source: 'datadog'
        smhi_source: smhi

        update: 'True'

borstahusenspir:
        url: 'http://seadog.ddns.net:800/rapporter/BSS.htm'
        kollaDessaClasser:
                storhetClassName: Kol_tx_storhet
                medelClassName: Kol_tx_medel
                minClassName: Kol_tx_mi
                maxClassName: Kol_tx_ma
        typeName:
                Kol_tx_medel: _medel
                Kol_tx_mi: _min
                Kol_tx_ma: _max

smhi:
        urlprefix: 'http://opendata-download-ocobs.smhi.se/api/version/latest/parameter/6/station/'
        seaLevelLocations: 
                Barseback: 2099
                Viken: 2228
                Klagshamn: 2095
                Skanor: 30488
